setw -g mode-keys vi

set -g mouse on
# to enable mouse scroll, see https://github.com/tmux/tmux/issues/145#issuecomment-150736967
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

set -g @plugin 'tmux-plugins/tmux-yank'

bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind C-a neww "joplin" \; rename-window "appunti"
bind C-s break-pane
bind-key @ join-pane -h -s !
